### ISSUE TITLE
There is a plain text password in the github actions

### ISSUE THREAD

**Issue by mbenabda** [google/openhtf#1007]
Looks like there is a plain text password for publishing the pypi package in 
https://github.com/google/openhtf/blob/master/.github/workflows/build_and_deploy.yml#L45

**Comment by glados-verma** [comment]
Hi Mehdi - you can check from https://pypi.org/project/openhtf/#history that there's been no release since Oct 14 2019. I've confirmed with the token owner that they pushed this version.

The token has been replaced, and the old one will be revoked by early next week. After that, we'll push a new version to PyPi. At that point, you could try doing a diff vs the GitHub code to double check from your side that there's no surprising diff.
