### ISSUE TITLE
Add UploadToMfgInspector to names.py for easy access

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#124]
Add UploadToMfgInspector to names.py for easy access

**Comment by jettisonjoe** [comment]
I'm torn on this. We don't want to crowd 'names' too much since we're recommending people import * from it for the easiest test authoring syntax. By that logic, things that people will swap out like individual plugs and output modules shouldn't be put into 'names'.

At the top of your test script could you do a 'from' import of UploadToMfgInspector instead?

**Comment by wallacbe** [comment]
Acknowledged, closing issue
