### ISSUE TITLE
Setting unbounded measurement to None results in fail

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#156]
Observed that setting unbounded measurement to None results in State.FAIL status.  Is this expected behavior?

**Comment by wallacbe** [comment]
https://github.com/google/openhtf/issues/4 appears to be related to this

**Comment by jettisonjoe** [comment]
I think we had tabled this with the intention of doing something sensible when we move measurement validation to the time of setting. Fixing #4 should fix this.

**Comment by grybmadsci** [comment]
Updates to measurements have included a separate flag to track whether a measurement has been set or not, rather than using None to indicate "not set".  So now setting to None is a valid thing.  Unset measurements still cause the test to FAIL (we can discuss that separately), but setting a measurement to None no longer makes it revert to UNSET.
