### ISSUE TITLE
Log measurements values as they're set.

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#338]
In my code I'm finding I'm logging value and setting the measurement a lot.
test.logger.info('gain: %d', gain)
test.measurements.gain = gain  

Can we have measurements log this behind the scenes?  Something like "param: value unit" or something similar.

**Comment by fahhem** [comment]
Why are you logging the measurement? The measurement values are already
available. Is this so that you can see progress? The web UI will show that
progress, hopefully.





On Wed, Jun 22, 2016 4:25 PM, wallacbe notifications@github.com wrote:
In my code I'm finding I'm logging value and setting the measurement a lot.
test.logger.info('gain: %d', gain)
test.measurements.gain = gain

Can we have measurements log this behind the scenes? Something like "param:
value unit" or something similar.

**Comment by wallacbe** [comment]
This is to progress in the CLI.
