### ISSUE TITLE
Test details are missing in local web front end

### ISSUE THREAD

**Issue by agdeepak** [google/openhtf#457]
Local web front end only displays Test Phase name and does not display any test details like Test name, Test start time, Test end time, Mode (offline, engr, prod?) etc. 

Screenshot attached.
![openhtf-frontend-example-starttime](https://cloud.githubusercontent.com/assets/16326136/20201102/6e9768ce-a76a-11e6-964a-c115031fee6f.PNG)

**Comment by fahhem** [comment]
This seems to be a problem with the new frontend that should have been fixed in the past two weeks. Please retry and open a new issue if it's still a problem. If you run into other problems, please check the open pull requests #519, #523, and #524. If they're relevant, merge them in and give that a try.
