### ISSUE TITLE
logging.info not showing up in console output

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#46]
Not seeing logging.info() show up in the console output.

In the example I don't see the "Tearing Down" or if I add logging.info to the phase I don't see output.

**Comment by amyxchen** [comment]
Console output default level is warning. if you want to see the info level logging, use flag "--verbosity info".  

--verbosity is for console level logging, for log file level, use "--log_file" to set the log file name, use "--log_level"  to set the log file logging level. (debug, info, warning, error, critical).

**Comment by wallacbe** [comment]
I added --verbosity info and I see the INFO about starting the phase
However I don't see the output from within the phase test.logger.info('blah')

**Comment by jettisonjoe** [comment]
We separated framework versus tester logging by design, and the command line flags were set up to control framework logging, with tester logging going to the test record (and from there to the output module). Maybe we can talk about this at our next in person meeting and see how we should handle the need for tester console output.

**Comment by wallacbe** [comment]
I've been adding the following to my phases and I'm able to see the output.  Maybe openhtf can do something similar?

import logging
logging.basicConfig()
logger = logging.getLogger()
logger.setLevel(logging.INFO)

**Comment by wallacbe** [comment]
Ran from head, I see output in the expected places, closing issue
