### ISSUE TITLE
The web GUI is not notified of changes to plug states

### ISSUE THREAD

**Issue by Kenadia** [google/openhtf#483]
This issue was initially detected as part of issue #479.

The Station API is not notified of changes to plug states. Therefore the frontend web GUI is not notified of changes to plug states. The result is that whether or not a prompt shows up on the front end is a race condition. If the prompt is at the start of a phase, it will usually show up.

Note that `StationAPI` has a `wait_for_plug` method but it's not currently used anywhere.

Below is a short script that demonstrates the problem. If you run this script, the first prompt should show up, but the second prompt should not show up due to the delay. If you refresh the page the second prompt should then show up.

```python
import openhtf
import time

from openhtf.plugs import user_input


@openhtf.plugs.plug(user_input=user_input.UserInput)
def delayed_prompt_phase(test, user_input):
  test.test_record.dut_id = 'my-dut-id'
  print 'Waiting one second.'
  time.sleep(1)
  result = user_input.prompt('Prompt: enter some input', text_input=True)


if __name__ == '__main__':
  openhtf.Test(delayed_prompt_phase, delayed_prompt_phase).execute()
```

**Comment by fahhem** [comment]
This is basically because the plug has no `notify_update` mechanism. The `wait_for_plug` method is a way to spend 100% CPU on it, by asking the plug to serialize it's state in a tight loop, but I think we can do better.

What if we created a `FrontendAwareBasePlug` or similar plug so that it was opt-in, but if they did opt-in they now had to call `self._state_updated.set()` every time the state is updated. Then, the base-class would have `self._state_updated = threading.Event` and a way for the Station API to subscribe to it, in the same way it subscribes to the event underlying `notify_update` in the test executor.
