### ISSUE TITLE
pypi release 1.2.0 is missing built proto files in openhtf/output/proto

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#693]
pypi release 1.2.0 is missing built proto files in openhtf/output/proto.  They are present in release 1.1.0.   This is observed by downloading the tarball from pypi.  Can this be corrected?  Thanks

**Comment by jettisonjoe** [comment]
Turns out the setup.py fail was only one of the problems. The other is that the .proto files were missing from our package definition, so they never have the chance to get built into .py's during package installation. I'm not sure what changed to make this a problem, or how long it has been a problem, but #705 should fix it.
